# Generated by Django 3.1 on 2020-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201028_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet_blog',
            field=models.CharField(default='Add a Snippet.', max_length=500),
        ),
    ]
